name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.2
        env:
          # Disable building for PyPy, 32bit and Python 3.10.
          CIBW_SKIP: pp* *-win32 *-manylinux_i686 cp310-*
          # Run the tests.
          CIBW_BEFORE_TEST: pip install -r requirements_test.txt
          CIBW_TEST_COMMAND: pytest {project}/tests

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
